# Required secrets:
# REMOTE_HOST
# REMOTE_USER
# SSH_PWD
# REMOTE_FOLDER

name: Build and deploy

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy tar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          passphrase: ${{ secrets.SSH_PWD }}
          target: ${{ secrets.REMOTE_FOLDER }}
          rm: false
          source: "canvas/*"
          strip_components: 1